//PACKAGE NET.SHOP.MYSHOPBACKEND.TEST;
//
//
//IMPORT STATIC ORG.JUNIT.ASSERT.ASSERTEQUALS;
//
//IMPORT ORG.JUNIT.BEFORECLASS;
IMPORT ORG.JUNIT.TEST;
IMPORT ORG.SPRINGFRAMEWORK.CONTEXT.ANNOTATION.ANNOTATIONCONFIGAPPLICATIONCONTEXT;
//
//IMPORT NET.SHOP.MYSHOPBACKEND.DAO.VEHICULEDAO;
//IMPORT NET.SHOP.MYSHOPBACKEND.DTO.VEHICULE;
//IMPORT NET.SHOP.MYSHOPBACKEND.DAOIMPL.*;
//
//PUBLIC CLASS VEHICULETESTCASE{
//	
//
//	PRIVATE STATIC ANNOTATIONCONFIGAPPLICATIONCONTEXT CONTEXT;
//	
//	PRIVATE STATIC VEHICULEDAO VEHICULEDAO;
//	
//	PRIVATE VEHICULE VEHICULE;
//	
//	
//	@BEFORECLASS
//	PUBLIC STATIC VOID INIT() {
//		CONTEXT = NEW ANNOTATIONCONFIGAPPLICATIONCONTEXT();
//		CONTEXT.SCAN("NET.SHOP.MYSHOPBACKEND");
//		CONTEXT.REFRESH();
//		VEHICULEDAO = (VEHICULEDAO)CONTEXT.GETBEAN("VEHICULEDAO");
//	}
//	
////	@TEST
////	PUBLIC VOID TESTCRUDPRODUCT() {
////		
////		// CREATE OPERATION
////		VEHICULE = NEW VEHICULE();
////				
////		VEHICULE.SETNAME("CAMION 125");
////		VEHICULE.SETBRAND("CAMIONNC");
////		VEHICULE.SETDESCRIPTION("THIS IS SOME DESCRIPTION FOR CAMION !");
////		VEHICULE.SETUNITPRICE(25000);
////		VEHICULE.SETACTIVE(TRUE);
////		VEHICULE.SETCATEGORYID(3);
////		VEHICULE.SETSUPPLIERID(3);
////		VEHICULE.SETHAUTEUR(5);
////		VEHICULE.SETLARGEUR(9);  
////		VEHICULE.SETPOIDS(50);
////		VEHICULE.SETNBR_PERSON(5);
////		VEHICULE.SETQUANTITY(70);
////		VEHICULE.SETVIEWS(0);
////		
////		ASSERTEQUALS("SOMETHING WENT WRONG WHILE INSERTING A NEW PRODUCT!",
////				TRUE,VEHICULEDAO.ADD(VEHICULE));		
////		
////		
////		// READING AND UPDATING THE CATEGORY
////		VEHICULE = VEHICULEDAO.GET(7);
////		VEHICULE.SETNAME("SAMSUNG GALAXY S7");
////		ASSERTEQUALS("SOMETHING WENT WRONG WHILE UPDATING THE EXISTING RECORD!",
////				TRUE,VEHICULEDAO.UPDATE(VEHICULE));		
////				
////		ASSERTEQUALS("SOMETHING WENT WRONG WHILE DELETING THE EXISTING RECORD!",
////				TRUE,VEHICULEDAO.DELETE(VEHICULE));		
////		
////		// LIST
////		ASSERTEQUALS("SOMETHING WENT WRONG WHILE FETCHING THE LIST OF PRODUCTS!",
////				5,VEHICULEDAO.LIST().SIZE());		
////				
////	}
////			
////	
////	@TEST
////	PUBLIC VOID TESTLISTACTIVEPRODUCTS() {
////		ASSERTEQUALS("SOMETHING WENT WRONG WHILE FETCHING THE LIST OF PRODUCTS!",
////				5,VEHICULEDAO.LISTACTIVEVEHICULES().SIZE());				
////	} 
////	
//	
////	@TEST
////	PUBLIC VOID TESTLISTACTIVEPRODUCTSBYCATEGORY() {
////		ASSERTEQUALS("SOMETHING WENT WRONG WHILE FETCHING THE LIST OF PRODUCTS!",
////				3,VEHICULEDAO.LISTACTIVEVEHICULESBYCATEGORY(3).SIZE());
////		ASSERTEQUALS("SOMETHING WENT WRONG WHILE FETCHING THE LIST OF PRODUCTS!",
////				2,VEHICULEDAO.LISTACTIVEVEHICULESBYCATEGORY(1).SIZE());
////	} 
//	
//	@TEST
	PUBLIC VOID TESTGETLATESTACTIVEPRODUCT() {
		ASSERTEQUALS("SOMETHING WENT WRONG WHILE FETCHING THE LIST OF PRODUCTS!",
//				3,VEHICULEDAO.GETLATESTACTIVEVEHICULES(3).SIZE());
//		
//	} 
//
//	
//
//	
//	
//}
